#!/usr/bin/env python3
"""Build the AI SEO TOFU/MOFU content plan -> 7 CSVs (6 goals + pillars).

TOPIC_SLUG=ai-seo  DOMAIN=SEO  AUTHOR=kim  DIMENSION=Discipline
Composed from data/entity_map.yml -> ai-seo block (435 entities, 26 categories).
Deduplicated against existing content/ as of 2026-06-09.
"""
import csv, os, base64

OUT = os.path.dirname(os.path.abspath(__file__))
AUTHOR = "kim"

COLUMNS = [
    "Topic", "Slug", "Content type", "Discipline", "Category", "Funnel stage",
    "Notes", "Needs experience?", "Expert / Author", "Section for insight",
    "Optional questions for expert", "Insight type", "Source of insight",
    "First-hand experience / Quote",
]

def row(topic, slug, ctype, disc, cat, funnel, notes="", needs="N",
        section="", questions="", insight="", source=""):
    return {
        "Topic": topic, "Slug": slug, "Content type": ctype, "Discipline": disc,
        "Category": cat, "Funnel stage": funnel, "Notes": notes,
        "Needs experience?": needs,
        "Expert / Author": AUTHOR if needs == "Y" or ctype == "Pillar" else AUTHOR,
        "Section for insight": section, "Optional questions for expert": questions,
        "Insight type": insight, "Source of insight": source,
        "First-hand experience / Quote": "",
    }

# convenience for the 3-question cell
def q(a, b, c):
    return f"1) {a}  2) {b}  3) {c}"

# =====================================================================
# PILLARS
# =====================================================================
pillars = [
 row("The Complete Guide to AI SEO (GEO + AEO)", "ai-seo-guide", "Pillar", "Strategy",
     "ai_seo_disciplines", "MOFU",
     "NEW master pillar. Service page ai-seo-services exists but is sales; this is the educational hub. Hub for all spokes below.",
     "Y", "Intro framing + 'how we think about AI SEO' section",
     q("Tell me about a client where layering GEO/AEO on top of classic SEO measurably changed pipeline — what did we actually do?",
       "What do most teams get wrong when they treat AI SEO as a separate department from SEO?",
       "Contrarian: where should a team NOT spend on AI SEO yet, and why?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("Generative Engine Optimization (GEO): The Complete Guide", "geo-guide", "Pillar", "AI Search",
     "ai_seo_disciplines", "MOFU",
     "NEW. best-geo-agencies (listicle) and best-saas-geo-agencies exist; no educational GEO pillar.",
     "Y", "'What actually moves GEO citations' section",
     q("Walk me through a client where a GEO play (brand mentions, citations, content restructure) lifted their share of model response.",
       "Which GEO tactics do you see overhyped vs underrated right now?",
       "How do you sequence GEO work for a brand starting from zero AI visibility?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("Answer Engine Optimization (AEO): The Complete Guide", "aeo-guide", "Pillar", "AI Search",
     "ai_seo_disciplines", "MOFU",
     "NEW. best-aeo-agency (listicle) exists; no AEO educational pillar.",
     "Y", "'Structuring content to be the answer' section",
     q("Show me a page we restructured for AEO that started getting pulled into AI Overviews / featured snippets — what changed?",
       "What's the most common AEO formatting mistake you fix on audits?",
       "How do you decide which pages are even AEO candidates?"),
     "Experience + Pull-quote", "audits"),
 row("AI SEO Strategy & Framework", "ai-seo-strategy-and-framework", "Pillar", "Strategy",
     "ai_seo_disciplines", "MOFU",
     "NEW. saas-seo-strategies-and-framework exists but is classic SEO; this is the AI-search strategy layer.",
     "Y", "Our AI-search prioritisation framework",
     q("How do you decide a client's first 90 days of AI SEO — what gets sequenced first?",
       "What does most teams' AI SEO strategy get backwards?",
       "How do you balance budget between classic SEO and GEO/AEO for a Series A vs Series C SaaS?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to Create Content That Gets Cited by AI", "ai-content-that-gets-cited", "Pillar", "Content",
     "geo_optimization_tactics", "MOFU",
     "EXPAND — overlaps how-to-write-saas-seo-content-with-ai-that-actually-ranks (live). Decide: expand that page into the pillar OR new hub that links to it.",
     "Y", "Our content-for-citation playbook",
     q("Tell me about a piece of content we built specifically to be citation-bait that worked.",
       "What makes content 'pullable' by an LLM that most writers miss?",
       "Statistics vs quotes vs original research — what earns citations fastest in your experience?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("Technical AI SEO: Crawlers, Schema & llms.txt", "technical-ai-seo-guide", "Pillar", "Technical",
     "ai_crawlers_access", "MOFU", "NEW.",
     "Y", "Technical AI-readiness audit walkthrough",
     q("Tell me about a client whose AI visibility was blocked by a technical issue (rendering, blocked crawler) — how did we find and fix it?",
       "Is llms.txt worth implementing, based on what you've actually seen?",
       "What technical AI-SEO checks belong in every audit now that didn't a year ago?"),
     "Experience + Pull-quote", "audits"),
 row("Building Brand Authority for AI Citations", "ai-seo-brand-authority", "Pillar", "Authority",
     "offsite_brand_presence", "MOFU", "NEW.",
     "Y", "Off-site brand-signal playbook",
     q("Tell me about a client where off-site presence (Reddit, Wikipedia, G2, PR) moved their AI citations.",
       "Brand search volume vs backlinks — which matters more for AI citations in your experience?",
       "How do you build 'being in the right rooms' for a brand AI doesn't yet recognise?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to Measure AI Search Visibility", "measuring-ai-search-visibility", "Pillar", "AI Search",
     "ai_visibility_metrics", "MOFU", "NEW.",
     "Y", "Our AI-visibility measurement stack",
     q("What's in our actual AI-visibility tracking stack and why those tools?",
       "Which AI visibility metrics are vanity vs which predict pipeline?",
       "How do you set a realistic AI-visibility baseline and target for a client?"),
     "Experience + Pull-quote", "team stack"),
 row("Programmatic SEO for AI Search", "programmatic-seo-for-ai-search", "Pillar", "Programmatic",
     "geo_optimization_tactics", "MOFU",
     "NEW. programmatic-seo-agency (service) exists; no programmatic-for-AI educational pillar.",
     "Y", "Programmatic-at-scale-without-thin-content section",
     q("Tell me about a programmatic content build that AI engines actually cited rather than ignored.",
       "Where does programmatic SEO go wrong for AI search specifically?",
       "How do you keep programmatic pages 'citation-worthy' and not thin?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("AI SEO for B2B SaaS", "ai-seo-for-b2b-saas", "Pillar", "Segment",
     "funnel_buyer_context", "MOFU",
     "NEW. b2b-saas-seo exists (classic). This is the AI-search angle for SaaS buying journeys.",
     "Y", "SaaS-buyer-journey-meets-AI-search section",
     q("How are B2B SaaS buyers actually using ChatGPT/Perplexity in their research, from what we see in client data?",
       "What's different about AI SEO for SaaS vs other verticals?",
       "Which funnel stage gets the biggest AI-search lift for SaaS clients?"),
     "Experience + Pull-quote", "Pull from client work"),
]

# =====================================================================
# GOAL 1 — Get discovered by AI engines & search
# =====================================================================
goal1 = [
 # Glossary (TOFU, N)
 row("What is Answer Engine Optimization (AEO)?", "what-is-aeo", "Glossary", "AI Search", "ai_seo_disciplines", "TOFU", "NEW"),
 row("What is Generative Engine Optimization (GEO)?", "what-is-geo", "Glossary", "AI Search", "ai_seo_disciplines", "TOFU", "NEW"),
 row("What is LLM Optimization (LLMO)?", "what-is-llmo", "Glossary", "AI Search", "ai_seo_disciplines", "TOFU", "NEW"),
 row("What are AI Overviews?", "what-is-ai-overviews", "Glossary", "AI Search", "ai_engines_answer_products", "TOFU", "NEW"),
 row("What is Google AI Mode?", "what-is-ai-mode", "Glossary", "AI Search", "ai_engines_answer_products", "TOFU", "NEW"),
 row("What is an answer engine?", "what-is-an-answer-engine", "Glossary", "AI Search", "ai_engines_answer_products", "TOFU", "NEW"),
 row("What is llms.txt?", "what-is-llms-txt", "Glossary", "Technical", "ai_crawlers_access", "TOFU", "NEW"),
 row("What is an AI crawler?", "what-is-an-ai-crawler", "Glossary", "Technical", "ai_crawlers_access", "TOFU", "NEW (covers GPTBot/PerplexityBot/ClaudeBot)"),
 row("What is entity SEO?", "what-is-entity-seo", "Glossary", "Authority", "knowledge_graph_entities", "TOFU", "NEW"),
 row("What is semantic SEO?", "what-is-semantic-seo", "Glossary", "Content", "ai_seo_disciplines", "TOFU", "NEW"),
 row("What is a knowledge graph?", "what-is-a-knowledge-graph", "Glossary", "Authority", "knowledge_graph_entities", "TOFU", "NEW"),
 row("What is a knowledge panel?", "what-is-a-knowledge-panel", "Glossary", "Authority", "knowledge_graph_entities", "TOFU", "NEW"),
 row("What is grounding (in AI)?", "what-is-grounding", "Glossary", "AI Search", "how_ai_search_works", "TOFU", "NEW"),
 row("What are embeddings?", "what-is-embeddings", "Glossary", "AI Search", "how_ai_search_works", "TOFU", "NEW (keep practitioner-level)"),
 row("What is vector search?", "what-is-vector-search", "Glossary", "AI Search", "how_ai_search_works", "TOFU", "NEW (keep practitioner-level)"),
 row("What is query fan-out?", "what-is-query-fan-out", "Glossary", "AI Search", "how_ai_search_works", "TOFU", "NEW"),
 row("What is named entity recognition (NER)?", "what-is-ner", "Glossary", "Authority", "knowledge_graph_entities", "TOFU", "NEW"),
 row("What is a context window?", "what-is-context-window", "Glossary", "AI Search", "llm_concepts_in_ai_seo", "TOFU", "NEW"),
 row("What is fine-tuning?", "what-is-fine-tuning", "Glossary", "AI Search", "llm_concepts_in_ai_seo", "TOFU", "NEW"),
 row("What is zero-click search?", "what-is-zero-click-search", "Glossary", "Strategy", "ai_seo_research_concepts", "TOFU", "NEW"),
 # Diagnostic blogs (TOFU, Y)
 row("GEO vs SEO: what's actually different in 2026", "geo-vs-seo", "Blog", "Strategy", "discipline_comparisons", "TOFU", "NEW", "Y",
     "Our take on where they diverge",
     q("Where have you seen GEO and SEO pull in genuinely different directions for a client?",
       "What's the biggest misconception teams have about GEO replacing SEO?",
       "If a client only had budget for one this quarter, how do you decide?"),
     "Experience", "PR POV"),
 row("AEO vs GEO: which should you prioritise?", "aeo-vs-geo", "Blog", "Strategy", "discipline_comparisons", "TOFU", "NEW", "Y",
     "Prioritisation heuristic",
     q("Give an example client where AEO mattered more than GEO (or vice versa) and why.",
       "What signals tell you a brand should start with AEO vs GEO?",
       "How do you explain the difference to a skeptical CMO?"),
     "Experience", "Pull from client work"),
 row("How AI search engines decide which sources to cite", "how-ai-engines-pick-sources", "Blog", "AI Search", "how_ai_search_works", "TOFU", "NEW", "Y",
     "What we've observed picking apart citations",
     q("From the citations we've analysed, what actually correlates with getting picked?",
       "What do people wrongly assume drives AI citations?",
       "How do you reverse-engineer why a competitor gets cited and a client doesn't?"),
     "Experience + Pull-quote", "audits"),
 row("Why your content isn't showing up in ChatGPT", "why-content-not-in-chatgpt", "Blog", "AI Search", "how_ai_search_works", "TOFU", "NEW", "Y",
     "Diagnostic checklist from real audits",
     q("What are the most common reasons a client's content is invisible to ChatGPT?",
       "What's the fastest-fix issue you see most often?",
       "When is it a content problem vs an authority problem?"),
     "Experience", "audits"),
 row("What makes a page citable by AI", "what-makes-a-page-citable", "Blog", "Content", "geo_optimization_tactics", "TOFU", "NEW", "Y",
     "Anatomy of a citation-friendly page",
     q("Walk through a page we made and AI started citing — what were the ingredients?",
       "What page traits look good to humans but hurt AI extractability?",
       "How much is format vs authority?"),
     "Experience + Pull-quote", "Pull from client work"),
 # How-to blogs (MOFU, Y)
 row("How to get your site crawled by AI bots (GPTBot, PerplexityBot, ClaudeBot)", "allow-ai-crawlers", "Blog", "Technical", "ai_crawlers_access", "MOFU", "NEW", "Y",
     "robots.txt + rendering walkthrough",
     q("Tell me about a client blocking AI crawlers without realising it — how did we catch it?",
       "What's the right default policy on allowing vs blocking AI crawlers?",
       "How do you handle the allow-for-discovery vs protect-content tension?"),
     "Experience", "audits"),
 row("How to set up llms.txt (and whether it's worth it)", "how-to-set-up-llms-txt", "Blog", "Technical", "ai_crawlers_access", "MOFU", "NEW", "Y",
     "Implementation + honest verdict",
     q("Have we implemented llms.txt for anyone, and did it change anything measurable?",
       "Why is llms.txt contested — what's your read?",
       "If a client insists on it, how do you implement it well?"),
     "Experience", "Fresh"),
 row("How to build a brand entity Google's Knowledge Graph recognises", "build-brand-entity-knowledge-graph", "Blog", "Authority", "knowledge_graph_entities", "MOFU", "NEW", "Y",
     "Entity-seeding playbook",
     q("Walk me through getting a client into the Knowledge Graph / earning a Knowledge Panel.",
       "What entity-consistency mistakes block recognition?",
       "How long does it realistically take and what's the sequence?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to get cited in Google AI Overviews", "how-to-get-cited-in-ai-overviews", "Blog", "AI Search", "ai_engines_answer_products", "MOFU", "NEW", "Y",
     "AI Overviews optimisation steps",
     q("Show me a client page that started appearing in AI Overviews — what we changed.",
       "What's overrated vs underrated for AI Overviews specifically?",
       "How do you target the queries most likely to trigger an AI Overview?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to get cited by Perplexity", "how-to-get-cited-by-perplexity", "Blog", "AI Search", "ai_engines_answer_products", "MOFU", "NEW", "Y",
     "Perplexity-specific tactics",
     q("What's worked specifically for Perplexity citations vs ChatGPT?",
       "Why does Perplexity lean so hard on certain source types?",
       "How do you tailor a page for Perplexity's retrieval?"),
     "Experience", "Pull from client work"),
 row("How to optimise for Google AI Mode", "how-to-optimise-for-ai-mode", "Blog", "AI Search", "ai_engines_answer_products", "MOFU", "NEW", "Y",
     "AI Mode + Deep Search tactics",
     q("What have we learned about ranking inside AI Mode / Deep Search?",
       "How is optimising for AI Mode different from AI Overviews?",
       "What query types does AI Mode reward?"),
     "Experience", "Fresh"),
 row("How to appear in ChatGPT search results", "how-to-appear-in-chatgpt", "Blog", "AI Search", "ai_engines_answer_products", "MOFU",
     "EXISTS — live at /blogs/how-to-rank-on-chatgpt-in-2026-strategies-and-tips/. EXPAND/refresh rather than new.", "Y",
     "n/a — refresh existing",
     q("(refresh) What's changed since the original ChatGPT-ranking post?",
       "(refresh) Any new client results to fold in?",
       "(refresh) Which original tactics have decayed?"),
     "Experience", "Pull from client work"),
]

# =====================================================================
# GOAL 2 — Win the citation / earn the visit
# =====================================================================
goal2 = [
 row("What is a featured snippet?", "what-is-a-featured-snippet", "Glossary", "Content", "classic_seo_bridge", "TOFU", "NEW"),
 row("What is position zero?", "what-is-position-zero", "Glossary", "Content", "classic_seo_bridge", "TOFU", "NEW"),
 row("What is E-E-A-T?", "what-is-e-e-a-t", "Glossary", "Authority", "compliance_trust", "TOFU", "NEW"),
 row("What is an AI citation?", "what-is-an-ai-citation", "Glossary", "AI Search", "ai_visibility_metrics", "TOFU", "NEW"),
 row("What is snippet extractability (pullability)?", "what-is-snippet-extractability", "Glossary", "Content", "how_ai_search_works", "TOFU", "NEW"),
 row("What is the inverted pyramid (in content)?", "what-is-inverted-pyramid", "Glossary", "Content", "geo_optimization_tactics", "TOFU", "NEW"),
 row("Featured snippets vs AI Overviews: what changed", "featured-snippets-vs-ai-overviews", "Blog", "Content", "discipline_comparisons", "TOFU", "NEW", "Y",
     "What we see in the SERP now",
     q("How has the shift from snippets to AI Overviews changed what we optimise for?",
       "Is 'position zero' still a useful goal?",
       "What still transfers from snippet optimisation to AEO?"),
     "Experience", "PR POV"),
 row("Why AI cites some pages and ignores others", "why-ai-cites-some-pages", "Blog", "Content", "geo_optimization_tactics", "TOFU", "NEW", "Y",
     "Citation patterns we've found",
     q("From our citation analyses, what separates cited from ignored pages?",
       "What's the single biggest lever?",
       "What surprised you when you dug into the data?"),
     "Experience + Pull-quote", "audits"),
 row("How to write answer-first content for AI", "answer-first-content", "Blog", "Content", "geo_optimization_tactics", "MOFU", "NEW", "Y",
     "BLUF / answer-first structure",
     q("Show me a before/after where answer-first restructuring won citations.",
       "What do writers resist about answer-first, and why are they wrong?",
       "How do you keep answer-first content from feeling thin?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to structure passages for AI extraction (chunking)", "structure-passages-for-ai", "Blog", "Content", "geo_optimization_tactics", "MOFU", "NEW", "Y",
     "Self-contained passage technique",
     q("How do you write self-contained passages without repeating yourself everywhere?",
       "What chunking mistakes hurt extractability?",
       "How granular should passages actually be?"),
     "Experience", "Pull from client work"),
 row("How to add citation-worthy statistics to your content", "citation-worthy-statistics", "Blog", "Content", "geo_optimization_tactics", "MOFU", "NEW", "Y",
     "Sourcing & pairing stats",
     q("Tell me about content where adding stats/original data drove citations.",
       "Where do teams get stat-sourcing wrong (and risk hallucinated cites)?",
       "Original research vs curated stats — when is each worth it?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to use schema markup to win AI citations", "schema-for-ai-citations", "Blog", "Technical", "structured_data_schema", "MOFU", "NEW", "Y",
     "Which schema types matter for AI",
     q("Which schema types have you seen actually correlate with AI citation?",
       "Is the attribute-rich vs bare-schema difference real in practice?",
       "What's the schema starter set you deploy on every client?"),
     "Experience", "audits"),
 row("How to write comparison pages that AI surfaces", "comparison-pages-for-ai", "Blog", "Content", "geo_optimization_tactics", "MOFU",
     "EXPAND — how-to-write-saas-comparison-pages-for-seo exists; add the AI-surface angle or cross-link.", "Y",
     "AI-surface angle on comparison pages",
     q("Have comparison/'best X' pages won AI citations for clients? Examples?",
       "What makes a comparison page trustworthy to an LLM?",
       "How do you handle being fair about competitors while still winning?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to format FAQs so AI answers pull from them", "faqs-for-ai-answers", "Blog", "Content", "structured_data_schema", "MOFU", "NEW", "Y",
     "FAQ structure + FAQPage schema",
     q("Have FAQ blocks earned answer-engine pickups for clients?",
       "What FAQ formatting fails to get extracted?",
       "Real questions vs keyword-stuffed FAQs — does it matter?"),
     "Experience", "Pull from client work"),
 row("How to optimise author bios for E-E-A-T and AI trust", "author-bios-for-eeat", "Blog", "Authority", "compliance_trust", "MOFU", "NEW", "Y",
     "Author entity & markup",
     q("Have author-entity improvements moved AI trust/citations for a client?",
       "What do most author bios miss for E-E-A-T?",
       "How do you build author authority from scratch?"),
     "Experience", "Pull from client work"),
 # Listicles (MOFU, N) — SERP confirmed listicle-shaped
 row("Best AI content optimisation tools", "best-ai-content-optimization-tools", "Listicle", "Content", "ai_content_optimization_tools", "MOFU", "NEW — SERP is listicle-shaped"),
 row("Best schema markup generators for SEO", "best-schema-markup-generators", "Listicle", "Technical", "structured_data_schema", "MOFU", "NEW — SERP is listicle-shaped"),
]

# =====================================================================
# GOAL 3 — Win on AI surfaces (GEO/AEO)
# =====================================================================
goal3 = [
 row("What is relevance engineering?", "what-is-relevance-engineering", "Glossary", "AI Search", "ai_seo_disciplines", "TOFU", "NEW"),
 row("What is Search Everywhere Optimization?", "what-is-search-everywhere-optimization", "Glossary", "Strategy", "ai_seo_disciplines", "TOFU", "NEW"),
 row("What is agentic AI?", "what-is-agentic-ai", "Glossary", "AI Search", "agentic_ai_search", "TOFU", "NEW"),
 row("What is Agentic Engine Optimization (AgEO)?", "what-is-ageo", "Glossary", "AI Search", "agentic_ai_search", "TOFU", "NEW — frontier term"),
 row("What is NLWeb?", "what-is-nlweb", "Glossary", "Technical", "agentic_ai_search", "TOFU", "NEW — frontier"),
 row("What is the GEO research paper (Aggarwal et al.)?", "what-is-the-geo-paper", "Glossary", "AI Search", "ai_seo_research_concepts", "TOFU", "NEW — explainer of the canonical study"),
 row("GEO tactics that actually move citations (and ones that don't)", "geo-tactics-that-work", "Blog", "AI Search", "geo_optimization_tactics", "MOFU", "NEW", "Y",
     "Tested vs hype tactics",
     q("Which GEO tactics have you seen produce real citation lift for clients?",
       "Which popular GEO 'hacks' have decayed or never worked (e.g. Reddit hacks, keyword stuffing for LLMs)?",
       "How do you test whether a tactic is working?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("Is llms.txt worth it? An honest assessment", "is-llms-txt-worth-it", "Blog", "Technical", "ai_crawlers_access", "TOFU", "NEW", "Y",
     "Our verdict",
     q("Have we A/B-observed any llms.txt impact?",
       "Why do you think the industry is split on it?",
       "What would change your mind about recommending it?"),
     "Experience", "Fresh"),
 row("Does keyword stuffing work for LLMs? (We tested the theory)", "keyword-stuffing-for-llms", "Blog", "Content", "geo_optimization_tactics", "TOFU", "NEW", "Y",
     "What the GEO paper + our tests show",
     q("Have you tried density-style tactics for LLM visibility — result?",
       "Why does the GEO paper find stuffing fails for generative engines?",
       "What should teams do instead?"),
     "Experience", "Fresh"),
 row("How to do GEO for ChatGPT", "geo-for-chatgpt", "Blog", "AI Search", "ai_engines_answer_products", "MOFU", "NEW", "Y",
     "ChatGPT-specific GEO",
     q("What's distinct about winning ChatGPT citations vs other engines?",
       "Where do teams waste effort optimising for ChatGPT?",
       "How do you track and iterate on ChatGPT visibility?"),
     "Experience", "Pull from client work"),
 row("How to do AEO for Google AI Overviews", "aeo-for-ai-overviews", "Blog", "AI Search", "ai_engines_answer_products", "MOFU", "NEW", "Y",
     "AI Overviews AEO",
     q("Walk through an AEO win in AI Overviews for a client.",
       "What content structure does AI Overviews reward most?",
       "How do you pick AEO target queries?"),
     "Experience + Pull-quote", "audits"),
 row("How to do prompt mapping across the funnel", "prompt-mapping-across-funnel", "Blog", "Strategy", "geo_optimization_tactics", "MOFU", "NEW", "Y",
     "Prompt-to-funnel mapping method",
     q("How do you actually capture the real prompts buyers use at each stage?",
       "How is prompt mapping different from keyword mapping?",
       "What did prompt mapping reveal for a client that keywords hid?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to reverse-engineer the sources AI cites for your topic", "reverse-engineer-ai-citations", "Blog", "AI Search", "geo_optimization_tactics", "MOFU", "NEW", "Y",
     "Citation-mining workflow",
     q("Walk me through how we mine the sources AI cites in a client's category.",
       "What do those cited-source patterns tell you to do next?",
       "What tools/manual steps make this practical?"),
     "Experience", "team stack"),
 row("How to optimise for multimodal AI search (images, video, voice)", "multimodal-ai-search", "Blog", "Content", "multimodal_emerging_surfaces", "MOFU", "NEW", "Y",
     "Multimodal optimisation",
     q("Have images/video/transcripts driven AI citations for clients?",
       "What's overlooked about multimodal for B2B SaaS specifically?",
       "How do you prioritise multimodal vs text work?"),
     "Experience", "Fresh"),
 row("How to prepare your site for AI agents (the agent-ready web)", "prepare-site-for-ai-agents", "Blog", "Technical", "agentic_ai_search", "MOFU", "NEW — frontier", "Y",
     "Agent-readiness checklist",
     q("Are any clients seeing agent traffic yet — what does it look like?",
       "What does 'agent-ready' actually require (NLWeb, MCP, structured data)?",
       "Is this worth doing now or premature?"),
     "Experience", "Fresh"),
 row("Best GEO / AEO tracking tools", "best-geo-aeo-tracking-tools", "Listicle", "AI Search", "geo_aeo_tracking_tools", "MOFU", "NEW — SERP is listicle-shaped"),
 row("Best AI visibility / brand monitoring tools", "best-ai-visibility-tools", "Listicle", "AI Search", "geo_aeo_tracking_tools", "MOFU", "NEW — SERP is listicle-shaped"),
]

# =====================================================================
# GOAL 4 — Convert AI-sourced visitors
# =====================================================================
goal4 = [
 row("What is a BOFU keyword?", "what-is-a-bofu-keyword", "Glossary", "Strategy", "funnel_buyer_context", "TOFU", "NEW"),
 row("What is message match?", "what-is-message-match", "Glossary", "Content", "funnel_buyer_context", "TOFU", "NEW"),
 row("What is a niche persona page?", "what-is-a-niche-persona-page", "Glossary", "Content", "geo_optimization_tactics", "TOFU", "NEW"),
 row("Why AI-sourced traffic converts differently", "why-ai-traffic-converts-differently", "Blog", "Strategy", "funnel_buyer_context", "TOFU", "NEW", "Y",
     "What client analytics show",
     q("How does AI-referred traffic behave vs organic in client data?",
       "What assumptions about AI traffic turn out wrong?",
       "Which AI engines send the most sales-ready visitors?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to optimise BOFU pages for LLM-sourced buyers", "bofu-pages-for-llm-buyers", "Blog", "Content", "funnel_buyer_context", "MOFU", "NEW", "Y",
     "BOFU-for-AI-buyers playbook",
     q("Tell me about a BOFU page we reworked for AI-sourced buyers.",
       "What do AI-sent buyers expect that classic organic visitors don't?",
       "How do you shorten the path from AI answer to demo?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to write alternatives/comparison pages for AI-sourced buyers", "alternatives-pages-for-ai-buyers", "Blog", "Content", "geo_optimization_tactics", "MOFU", "NEW", "Y",
     "Alternatives-page angle",
     q("Have 'X alternatives' pages converted AI-sourced traffic for clients?",
       "What makes these pages credible to a buyer arriving from an LLM?",
       "How do you avoid the thin/templated trap?"),
     "Experience", "Pull from client work"),
 row("How to build niche persona pages that AI recommends", "niche-persona-pages", "Blog", "Content", "geo_optimization_tactics", "MOFU", "NEW", "Y",
     "Persona-page build",
     q("Walk me through a niche persona page ('X for fintech') that won AI recommendations.",
       "When do persona pages help vs dilute focus?",
       "How granular should persona pages get?"),
     "Experience", "Pull from client work"),
]

# =====================================================================
# GOAL 5 — Generate pipeline & prove ROI
# =====================================================================
goal5 = [
 row("What is the dark funnel?", "what-is-the-dark-funnel", "Glossary", "Strategy", "ai_visibility_metrics", "TOFU", "NEW"),
 row("What is self-reported attribution?", "what-is-self-reported-attribution", "Glossary", "Strategy", "ai_visibility_metrics", "TOFU", "NEW"),
 row("What is AI referral traffic?", "what-is-ai-referral-traffic", "Glossary", "Strategy", "ai_visibility_metrics", "TOFU", "NEW"),
 row("How to attribute pipeline to AI search", "attribute-pipeline-to-ai-search", "Blog", "Strategy", "ai_visibility_metrics", "MOFU", "NEW", "Y",
     "Our attribution approach",
     q("How do we actually connect AI search to pipeline for clients?",
       "Where does AI-search attribution break, and how do you work around it?",
       "Self-reported vs tracked — how do you blend them?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("The dark funnel problem in AI search (and how to handle it)", "dark-funnel-ai-search", "Blog", "Strategy", "ai_visibility_metrics", "TOFU", "NEW", "Y",
     "How we reason about hidden influence",
     q("How big is the dark-funnel effect in your client data for AI search?",
       "What do teams get wrong trying to fully attribute AI influence?",
       "How do you make the case for AI SEO when attribution is fuzzy?"),
     "Experience + Pull-quote", "PR POV"),
 row("How to track AI-attributed leads in GA4", "track-ai-leads-ga4", "Blog", "Technical", "ai_visibility_metrics", "MOFU", "NEW", "Y",
     "GA4 setup for AI referrers",
     q("What's our actual GA4 setup for isolating AI referral traffic?",
       "What breaks in GA4 for AI-source tracking and how do you fix it?",
       "Which segments/channel groups do you create?"),
     "Experience", "team stack"),
 row("How to measure pipeline from AI referral traffic", "measure-pipeline-from-ai-traffic", "Blog", "Strategy", "ai_visibility_metrics", "MOFU", "NEW", "Y",
     "Connecting traffic to CRM",
     q("How do you connect AI referral sessions to closed revenue in client setups?",
       "What's a realistic expectation for AI-sourced pipeline early on?",
       "Which metric do you put in front of the CFO?"),
     "Experience", "Pull from client work"),
 row("How to report AI SEO ROI to leadership", "report-ai-seo-roi", "Blog", "Strategy", "ai_visibility_metrics", "MOFU", "NEW", "Y",
     "The exec reporting view",
     q("What does our AI-SEO exec report actually contain?",
       "What do leaders care about vs what practitioners obsess over?",
       "How do you set expectations on timeline and proof?"),
     "Experience + Pull-quote", "Pull from client work"),
]

# =====================================================================
# GOAL 6 — Measure, scale & sustain
# =====================================================================
goal6 = [
 row("What is AI Share of Voice?", "what-is-ai-share-of-voice", "Glossary", "AI Search", "ai_visibility_metrics", "TOFU", "NEW"),
 row("What is an AI visibility score?", "what-is-ai-visibility-score", "Glossary", "AI Search", "ai_visibility_metrics", "TOFU", "NEW"),
 row("What is citation share?", "what-is-citation-share", "Glossary", "AI Search", "ai_visibility_metrics", "TOFU", "NEW"),
 row("What is Share of Model Response?", "what-is-share-of-model-response", "Glossary", "AI Search", "ai_visibility_metrics", "TOFU", "NEW"),
 row("What is pay-per-crawl?", "what-is-pay-per-crawl", "Glossary", "Technical", "ai_crawlers_access", "TOFU", "NEW — frontier (Cloudflare)"),
 row("AI visibility metrics that actually matter", "ai-visibility-metrics-that-matter", "Blog", "AI Search", "ai_visibility_metrics", "TOFU", "NEW", "Y",
     "Signal vs vanity",
     q("Which AI-visibility metrics do you actually report, and why those?",
       "Which metrics are vanity for AI search?",
       "How do you tie a visibility metric to a business outcome?"),
     "Experience + Pull-quote", "team stack"),
 row("How often AI citations change (and what to do about it)", "how-often-ai-citations-change", "Blog", "AI Search", "ai_seo_research_concepts", "TOFU", "NEW", "Y",
     "Volatility we've observed",
     q("How volatile are client AI citations month to month?",
       "What causes the churn, from what you've seen?",
       "How do you keep content from decaying out of AI answers?"),
     "Experience", "audits"),
 row("How to set up AI visibility tracking from scratch", "set-up-ai-visibility-tracking", "Blog", "AI Search", "geo_aeo_tracking_tools", "MOFU", "NEW", "Y",
     "Tracking-stack setup",
     q("What's our step-by-step for standing up AI-visibility tracking for a new client?",
       "What do teams set up wrong first?",
       "Which prompts/queries do you seed the tracking with?"),
     "Experience", "team stack"),
 row("How to monitor brand sentiment in AI answers", "monitor-brand-sentiment-in-ai", "Blog", "Authority", "ai_visibility_metrics", "MOFU", "NEW", "Y",
     "Sentiment monitoring",
     q("Have you caught (and fixed) negative/incorrect AI brand answers for a client?",
       "How do you correct what an LLM 'believes' about a brand?",
       "What's the workflow for ongoing sentiment monitoring?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to manage AI crawlers: allow, block, or charge (pay-per-crawl)", "manage-ai-crawlers", "Blog", "Technical", "ai_crawlers_access", "MOFU", "NEW", "Y",
     "Crawler-policy decision framework",
     q("How do you advise clients on allow vs block vs Cloudflare pay-per-crawl?",
       "What's the trade-off most teams underestimate?",
       "Where do you see this heading?"),
     "Experience", "PR POV"),
 row("How to scale GEO content production without losing quality", "scale-geo-content", "Blog", "Programmatic", "geo_optimization_tactics", "MOFU", "NEW", "Y",
     "Scaling with human-in-the-loop",
     q("How do we scale citation-worthy content without it going thin?",
       "Where does AI-assisted content production break quality?",
       "What's your human-in-the-loop QA standard?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to audit your AI search visibility", "ai-search-visibility-audit", "Blog", "AI Search", "ai_visibility_metrics", "MOFU", "NEW", "Y",
     "Our AI-visibility audit",
     q("Walk me through our AI-visibility audit end to end.",
       "What's the most common gap an audit surfaces?",
       "What quick wins come out of a typical audit?"),
     "Experience + Pull-quote", "audits"),
 row("Best AI rank tracking & monitoring tools", "best-ai-rank-tracking-tools", "Listicle", "AI Search", "geo_aeo_tracking_tools", "MOFU", "NEW — SERP is listicle-shaped"),
]

# =====================================================================
# EXPANSION PASS — push toward exhaustive (~200+ topics)
# =====================================================================

# --- Goal 1: engine glossaries, more diagnostics, per-engine how-tos, segments
goal1 += [
 row("What is generative AI?", "what-is-generative-ai", "Glossary", "AI Search", "llm_concepts_in_ai_seo", "TOFU", "NEW"),
 row("What is a transformer (AI model)?", "what-is-a-transformer", "Glossary", "AI Search", "llm_concepts_in_ai_seo", "TOFU", "NEW — practitioner-level"),
 row("What is tokenization?", "what-is-tokenization", "Glossary", "AI Search", "llm_concepts_in_ai_seo", "TOFU", "NEW"),
 row("What is training data (and the training cutoff)?", "what-is-training-data", "Glossary", "AI Search", "llm_concepts_in_ai_seo", "TOFU", "NEW"),
 row("What is Perplexity AI?", "what-is-perplexity-ai", "Glossary", "AI Search", "ai_engines_answer_products", "TOFU", "NEW"),
 row("What is Google Gemini?", "what-is-google-gemini", "Glossary", "AI Search", "ai_engines_answer_products", "TOFU", "NEW"),
 row("What is Microsoft Copilot?", "what-is-microsoft-copilot", "Glossary", "AI Search", "ai_engines_answer_products", "TOFU", "NEW"),
 row("What is Claude (Anthropic)?", "what-is-claude", "Glossary", "AI Search", "ai_engines_answer_products", "TOFU", "NEW"),
 row("What is passage ranking?", "what-is-passage-ranking", "Glossary", "AI Search", "how_ai_search_works", "TOFU", "NEW"),
 row("What is retrieval-augmented generation (RAG)?", "what-is-rag-for-seo", "Glossary", "AI Search", "how_ai_search_works", "TOFU",
     "DELETE/SKIP — already live at /glossary/what-is-rag/. Cross-link instead."),
 row("ChatGPT vs Perplexity vs Gemini: how each picks and cites sources", "chatgpt-vs-perplexity-vs-gemini-citations", "Blog", "AI Search", "ai_engines_answer_products", "TOFU", "NEW", "Y",
     "Engine-by-engine citation behaviour we've observed",
     q("From client tracking, how do citation patterns differ across the three engines?",
       "What do teams wrongly assume is the same across engines?",
       "If you could only optimise for one engine for B2B SaaS, which and why?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("Do backlinks still matter for AI search?", "do-backlinks-matter-for-ai-search", "Blog", "Authority", "ai_seo_research_concepts", "TOFU", "NEW", "Y",
     "Our read on links vs brand signals",
     q("In client data, how do backlinks vs brand mentions track against AI citations?",
       "What's the biggest misconception about links and AI search?",
       "Where would you still invest in links for AI visibility?"),
     "Experience", "PR POV"),
 row("How LLM training cutoffs affect your AI visibility", "training-cutoffs-and-visibility", "Blog", "AI Search", "llm_concepts_in_ai_seo", "TOFU", "NEW", "Y",
     "Training data vs live retrieval explained",
     q("Have you seen a client helped/hurt by a model's training cutoff?",
       "What do people misunderstand about training data vs live retrieval?",
       "How do you optimise for both at once?"),
     "Experience", "Fresh"),
 row("How to optimise for Microsoft Copilot", "optimise-for-microsoft-copilot", "Blog", "AI Search", "ai_engines_answer_products", "MOFU", "NEW", "Y",
     "Copilot / Bing-index tactics",
     q("What's worked for Copilot citations, given its Bing-index reliance?",
       "Why do teams ignore Copilot, and is that a mistake?",
       "How do you tie Copilot work to Bing Webmaster signals?"),
     "Experience", "Pull from client work"),
 row("How to optimise for Google Gemini", "optimise-for-gemini", "Blog", "AI Search", "ai_engines_answer_products", "MOFU", "NEW", "Y",
     "Gemini-specific tactics",
     q("What moves Gemini visibility vs AI Overviews (same model, different surface)?",
       "What's distinct about Gemini's sourcing?",
       "How do you track Gemini separately?"),
     "Experience", "Pull from client work"),
 row("How to optimise for Grok and DeepSeek", "optimise-for-grok-deepseek", "Blog", "AI Search", "ai_engines_answer_products", "MOFU", "NEW — emerging engines", "Y",
     "Emerging-engine tactics",
     q("Are any clients getting traffic from Grok/DeepSeek yet?",
       "Is it worth optimising for emerging engines now or premature?",
       "What's different about their sourcing?"),
     "Experience", "Fresh"),
 row("How to show up in AI shopping/product discovery (ChatGPT & Bing)", "ai-shopping-product-discovery", "Blog", "AI Search", "ai_engines_answer_products", "MOFU", "NEW — frontier commerce surface", "Y",
     "Product-discovery optimisation",
     q("Have we optimised any SaaS for ChatGPT shopping / product discovery?",
       "What product data do these surfaces need?",
       "How relevant is this for B2B vs B2C SaaS?"),
     "Experience", "Fresh"),
 # Segment / vertical AI-SEO how-tos (Discipline = Segment)
 row("How to do AI SEO for fintech SaaS", "ai-seo-for-fintech-saas", "Blog", "Segment", "funnel_buyer_context", "MOFU", "NEW — AI angle; fintech-seo-agency service page exists", "Y",
     "Fintech AI-search nuances (YMYL/trust)",
     q("What's specific about winning AI citations in fintech (YMYL, compliance)?",
       "What do fintech teams get wrong about AI SEO?",
       "How does trust/authority weigh differently here?"),
     "Experience", "Pull from client work"),
 row("How to do AI SEO for developer tools", "ai-seo-for-devtools", "Blog", "Segment", "funnel_buyer_context", "MOFU", "NEW — devtools-marketing-agency exists", "Y",
     "Devtools AI-search (docs, GitHub, Stack Overflow)",
     q("How do docs/GitHub/Stack Overflow presence drive AI citations for devtools?",
       "What's unique about how developers use AI search to evaluate tools?",
       "Where do devtools brands miss AI-visibility wins?"),
     "Experience", "Pull from client work"),
 row("How to do AI SEO for healthtech SaaS", "ai-seo-for-healthtech", "Blog", "Segment", "funnel_buyer_context", "MOFU", "NEW — healthtech-marketing-agency exists", "Y",
     "Healthtech AI-search (YMYL/E-E-A-T heavy)",
     q("How do you build the authority AI engines demand in health (YMYL)?",
       "What's riskiest about AI SEO in healthtech?",
       "How do you handle accuracy/hallucination concerns with clients?"),
     "Experience", "Pull from client work"),
 row("How to do AI SEO for cybersecurity SaaS", "ai-seo-for-cybersecurity", "Blog", "Segment", "funnel_buyer_context", "MOFU", "NEW — cybersecurity-marketing-agency exists", "Y",
     "Cybersecurity AI-search nuances",
     q("What earns AI citations in a credibility-obsessed category like security?",
       "What do security brands get wrong about AI SEO?",
       "How do you balance technical depth with extractability?"),
     "Experience", "Pull from client work"),
 row("How to do AI SEO for HR tech SaaS", "ai-seo-for-hrtech", "Blog", "Segment", "funnel_buyer_context", "MOFU", "NEW — hrtech-marketing-agency exists", "Y",
     "HR tech AI-search nuances",
     q("What's specific about AI-search buyer research in HR tech?",
       "Where do HR tech brands under-invest in AI visibility?",
       "Which content types win citations here?"),
     "Experience", "Pull from client work"),
 row("How to do AI SEO for martech SaaS", "ai-seo-for-martech", "Blog", "Segment", "funnel_buyer_context", "MOFU", "NEW — martech-marketing-agency exists", "Y",
     "Martech AI-search nuances",
     q("Martech is crowded — how do you win AI recommendations in it?",
       "What do martech brands get wrong about GEO?",
       "How do you differentiate in AI answers?"),
     "Experience", "Pull from client work"),
]

# --- Goal 2: more glossary, tactics, diagnostics
goal2 += [
 row("What is BLUF (Bottom Line Up Front)?", "what-is-bluf", "Glossary", "Content", "geo_optimization_tactics", "TOFU", "NEW"),
 row("What is original research content?", "what-is-original-research-content", "Glossary", "Content", "geo_optimization_tactics", "TOFU", "NEW"),
 row("What is content freshness?", "what-is-content-freshness", "Glossary", "Content", "geo_optimization_tactics", "TOFU", "NEW"),
 row("What is author schema (authorship markup)?", "what-is-author-schema", "Glossary", "Technical", "structured_data_schema", "TOFU", "NEW"),
 row("What is co-citation?", "what-is-co-citation", "Glossary", "Authority", "offsite_brand_presence", "TOFU", "NEW"),
 row("Statistics vs quotes vs original research: what AI cites most", "stats-vs-quotes-vs-research", "Blog", "Content", "geo_optimization_tactics", "TOFU", "NEW", "Y",
     "What earns citations fastest",
     q("Across clients, which content asset earns AI citations fastest?",
       "Where do teams waste effort on the wrong citation-bait?",
       "How do you decide when original research is worth the cost?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to keep content fresh and avoid AI citation decay", "avoid-ai-citation-decay", "Blog", "Content", "ai_seo_research_concepts", "MOFU", "NEW", "Y",
     "Freshness cadence",
     q("How often do you refresh to hold AI citations, from experience?",
       "What signals that a page is decaying out of AI answers?",
       "What's your update workflow?"),
     "Experience", "Pull from client work"),
 row("How to win co-citations alongside category leaders", "win-co-citations", "Blog", "Authority", "offsite_brand_presence", "MOFU", "NEW", "Y",
     "Co-citation engineering",
     q("Tell me about engineering a brand to appear next to category terms/leaders.",
       "Why does co-occurrence matter so much for AI?",
       "What's the practical playbook to build it?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to use TL;DR and summary blocks for AI extraction", "tldr-blocks-for-ai", "Blog", "Content", "geo_optimization_tactics", "MOFU", "NEW", "Y",
     "Summary-block technique",
     q("Have TL;DR/summary blocks measurably helped citation pickups?",
       "Where do summary blocks backfire?",
       "How do you write one that AI lifts cleanly?"),
     "Experience", "Pull from client work"),
 row("How to use internal entity linking for AI search", "internal-entity-linking", "Blog", "Authority", "knowledge_graph_entities", "MOFU", "NEW", "Y",
     "Entity-linking method",
     q("How does internal entity linking change AI's understanding of a site?",
       "What's the difference vs normal internal linking?",
       "What's your linking pattern for entity reinforcement?"),
     "Experience", "audits"),
 row("How to optimise images for AI search (ImageObject schema)", "optimise-images-for-ai", "Blog", "Technical", "structured_data_schema", "MOFU", "NEW", "Y",
     "Image/multimodal markup",
     q("Have image optimisations driven multimodal AI citations?",
       "What image-SEO steps matter now that didn't?",
       "How do you prioritise image work?"),
     "Experience", "Fresh"),
]

# --- Goal 3: more glossary, per-engine/discipline how-tos, diagnostics, listicle
goal3 += [
 row("What is llms-full.txt?", "what-is-llms-full-txt", "Glossary", "Technical", "ai_crawlers_access", "TOFU", "NEW"),
 row("What is semantic completeness?", "what-is-semantic-completeness", "Glossary", "Content", "geo_optimization_tactics", "TOFU", "NEW"),
 row("What is passage optimisation?", "what-is-passage-optimisation", "Glossary", "Content", "geo_optimization_tactics", "TOFU", "NEW"),
 row("What is prompt mapping?", "what-is-prompt-mapping", "Glossary", "Strategy", "geo_optimization_tactics", "TOFU", "NEW"),
 row("What is the Matthew Effect in AI citations?", "what-is-matthew-effect-ai", "Glossary", "AI Search", "ai_seo_research_concepts", "TOFU", "NEW"),
 row("GEO vs AEO vs LLMO: do the labels actually matter?", "geo-aeo-llmo-labels", "Blog", "Strategy", "ai_seo_disciplines", "TOFU", "NEW", "Y",
     "Our stance on the alphabet soup",
     q("Do these distinctions change what we actually do for a client?",
       "Why is the industry inventing so many acronyms?",
       "What framing do you give clients to cut through it?"),
     "Experience", "PR POV"),
 row("Will AI agents change SEO? Inside agentic search", "will-ai-agents-change-seo", "Blog", "AI Search", "agentic_ai_search", "TOFU", "NEW — frontier", "Y",
     "Our forward view",
     q("Any early signal of agent-driven behaviour in client data?",
       "What's hype vs real about the 'agent-ready web'?",
       "What should teams do today vs wait on?"),
     "Experience", "Fresh"),
 row("How to optimise for AI Mode Deep Search", "optimise-for-deep-search", "Blog", "AI Search", "ai_engines_answer_products", "MOFU", "NEW", "Y",
     "Deep Search tactics",
     q("What does Deep Search reward that standard AI Mode doesn't?",
       "How do you structure content for multi-query deep research?",
       "Have we seen Deep Search citations yet?"),
     "Experience", "Fresh"),
 row("How to do AEO for voice assistants", "aeo-for-voice-assistants", "Blog", "AI Search", "multimodal_emerging_surfaces", "MOFU", "NEW", "Y",
     "Voice-answer optimisation",
     q("Does voice-assistant optimisation still matter for B2B SaaS?",
       "What content format wins voice answers?",
       "How do you measure it?"),
     "Experience", "Fresh"),
 row("How to run query perturbation testing to find retrieval branches", "query-perturbation-testing", "Blog", "AI Search", "how_ai_search_works", "MOFU", "NEW — advanced", "Y",
     "Relevance-engineering technique",
     q("Walk me through perturbing queries to map what AI retrieves.",
       "What does this reveal that keyword tools don't?",
       "How practical is this for a normal team?"),
     "Experience", "team stack"),
 row("Best all-in-one AI SEO platforms", "best-ai-seo-platforms", "Listicle", "AI Search", "geo_aeo_tracking_tools", "MOFU", "NEW — SERP is listicle-shaped"),
]

# --- Goal 4: more glossary, diagnostics, how-tos
goal4 += [
 row("What is ToFu / MoFu / BoFu?", "what-is-tofu-mofu-bofu", "Glossary", "Strategy", "funnel_buyer_context", "TOFU", "NEW"),
 row("What is a comparison page?", "what-is-a-comparison-page", "Glossary", "Content", "geo_optimization_tactics", "TOFU", "NEW"),
 row("What is product-led content?", "what-is-product-led-content", "Glossary", "Content", "funnel_buyer_context", "TOFU", "NEW"),
 row("Why buyers trust AI recommendations (and what that means for you)", "why-buyers-trust-ai-recommendations", "Blog", "Strategy", "funnel_buyer_context", "TOFU", "NEW", "Y",
     "Buyer-trust dynamics",
     q("What do you see about how much buyers trust AI vendor recommendations?",
       "What does that change about how we position clients?",
       "Where is that trust misplaced or risky?"),
     "Experience", "PR POV"),
 row("How to optimise pricing pages for AI-sourced buyers", "pricing-pages-for-ai-buyers", "Blog", "Content", "funnel_buyer_context", "MOFU", "NEW", "Y",
     "Pricing-page-for-AI angle",
     q("Have pricing-page changes helped convert AI-sent buyers?",
       "What do AI-sent buyers want to see on pricing?",
       "How do you handle 'no public pricing' SaaS for AI search?"),
     "Experience", "Pull from client work"),
 row("How to build use-case pages that AI recommends", "use-case-pages-for-ai", "Blog", "Content", "geo_optimization_tactics", "MOFU", "NEW", "Y",
     "Use-case page build",
     q("Tell me about a use-case page that won AI recommendations.",
       "What makes a use-case page credible to an LLM?",
       "How many use-case pages is too many?"),
     "Experience", "Pull from client work"),
 row("How to win 'best [category] tool' AI recommendations", "win-best-category-recommendations", "Blog", "Content", "geo_optimization_tactics", "MOFU", "NEW", "Y",
     "Earning the recommendation slot",
     q("How do you get a client named when someone asks AI for the 'best [category]'?",
       "What drives inclusion in those AI shortlists?",
       "How much is on-site vs off-site/review presence?"),
     "Experience + Pull-quote", "Pull from client work"),
]

# --- Goal 5: more glossary, diagnostics, how-tos
goal5 += [
 row("What is pipeline-influenced revenue?", "what-is-pipeline-influenced-revenue", "Glossary", "Strategy", "ai_visibility_metrics", "TOFU", "NEW"),
 row("What is multi-touch attribution?", "what-is-multi-touch-attribution", "Glossary", "Strategy", "ai_visibility_metrics", "TOFU", "NEW"),
 row("What is brand search volume?", "what-is-brand-search-volume", "Glossary", "Authority", "ai_seo_research_concepts", "TOFU", "NEW"),
 row("Is AI search traffic worth the investment yet?", "is-ai-search-worth-it", "Blog", "Strategy", "ai_visibility_metrics", "TOFU", "NEW", "Y",
     "Our honest cost/benefit read",
     q("For which clients has AI SEO clearly paid back — and which not yet?",
       "What's the honest case against over-investing in AI SEO right now?",
       "How do you size the opportunity for a specific client?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to forecast AI SEO impact for a client", "forecast-ai-seo-impact", "Blog", "Strategy", "ai_visibility_metrics", "MOFU", "NEW", "Y",
     "Forecasting method",
     q("How do you build a credible AI-SEO forecast without overpromising?",
       "What assumptions blow up forecasts here?",
       "What range do you commit to vs caveat?"),
     "Experience", "Pull from client work"),
 row("How to build an AI SEO reporting dashboard", "ai-seo-dashboard", "Blog", "Strategy", "ai_visibility_metrics", "MOFU", "NEW", "Y",
     "Dashboard build",
     q("What's on our actual AI-SEO dashboard and which tools feed it?",
       "What metric do clients fixate on that you have to reframe?",
       "How do you blend tool data with GA4/CRM?"),
     "Experience", "team stack"),
 row("How to benchmark your AI visibility against competitors", "benchmark-ai-visibility", "Blog", "Strategy", "ai_visibility_metrics", "MOFU", "NEW", "Y",
     "Competitive benchmarking",
     q("How do you set a competitive AI-visibility benchmark for a client?",
       "What does a realistic 'catch up' timeline look like?",
       "Which competitor signals matter most?"),
     "Experience", "audits"),
]

# --- Goal 6: more glossary, tool setups, diagnostics, listicle
goal6 += [
 row("What is the Brand Visibility Index?", "what-is-brand-visibility-index", "Glossary", "AI Search", "ai_visibility_metrics", "TOFU", "NEW"),
 row("What is IndexNow?", "what-is-indexnow", "Glossary", "Technical", "ai_crawlers_access", "TOFU", "NEW"),
 row("What is content decay?", "what-is-content-decay", "Glossary", "Content", "ai_seo_research_concepts", "TOFU", "NEW"),
 row("What is prompt coverage?", "what-is-prompt-coverage", "Glossary", "AI Search", "ai_visibility_metrics", "TOFU", "NEW"),
 row("Build vs buy: do you need an AI visibility tool?", "build-vs-buy-ai-visibility-tool", "Blog", "AI Search", "geo_aeo_tracking_tools", "TOFU", "NEW", "Y",
     "When tools earn their cost",
     q("At what point does a client actually need a paid AI-visibility tool?",
       "What can you track free vs what needs a tool?",
       "Which tools have earned their keep in our stack?"),
     "Experience + Pull-quote", "team stack"),
 row("How to know if your GEO is actually working", "is-your-geo-working", "Blog", "AI Search", "ai_visibility_metrics", "TOFU", "NEW", "Y",
     "Leading vs lagging signals",
     q("What early signals tell you GEO is working before pipeline shows it?",
       "What false signals fool teams?",
       "How long before you expect to see movement?"),
     "Experience", "Pull from client work"),
 row("How to set up Profound for AI visibility tracking", "set-up-profound", "Blog", "AI Search", "geo_aeo_tracking_tools", "MOFU", "NEW", "Y",
     "Profound setup walkthrough",
     q("How do we configure Profound for a new client?",
       "What does Profound show that others miss?",
       "What setup mistakes waste its value?"),
     "Experience", "team stack"),
 row("How to track AI crawler traffic with Cloudflare Radar", "track-ai-crawler-traffic", "Blog", "Technical", "ai_crawlers_access", "MOFU", "NEW", "Y",
     "Crawler-traffic observability",
     q("What does AI-crawler traffic tell you that's actionable?",
       "How do you turn crawler data into content decisions?",
       "What surprised you in client crawler logs?"),
     "Experience", "audits"),
 row("How to operationalise GEO as an ongoing program", "operationalise-geo-program", "Blog", "Strategy", "agency_geo_frameworks", "MOFU", "NEW", "Y",
     "Running GEO as a program",
     q("What does a steady-state GEO program look like month to month?",
       "Where do one-off GEO efforts fail vs ongoing ones?",
       "How do you staff/resource it?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("Best AI content detection / originality tools", "best-ai-content-detection-tools", "Listicle", "Content", "ai_content_optimization_tools", "MOFU", "NEW — SERP is listicle-shaped"),
]

# =====================================================================
# EXPANSION PASS 2 — clear ~200 (kept off Goal 1 to respect base64 cap)
# =====================================================================
goal2 += [
 row("What is Schema.org?", "what-is-schema-org", "Glossary", "Technical", "structured_data_schema", "TOFU", "NEW"),
 row("What is FAQPage schema?", "what-is-faqpage-schema", "Glossary", "Technical", "structured_data_schema", "TOFU", "NEW"),
 row("What is HowTo schema?", "what-is-howto-schema", "Glossary", "Technical", "structured_data_schema", "TOFU", "NEW"),
 row("What is a pull-quote?", "what-is-a-pull-quote", "Glossary", "Content", "geo_optimization_tactics", "TOFU", "NEW"),
 row("How to write for humans and AI at the same time", "write-for-humans-and-ai", "Blog", "Content", "geo_optimization_tactics", "MOFU", "NEW", "Y",
     "Dual-audience writing",
     q("How do you keep content human-readable while making it AI-extractable?",
       "Where do teams over-optimise for machines and lose the reader?",
       "What's your editorial standard for getting both?"),
     "Experience", "Pull from client work"),
]
goal3 += [
 row("What is Grok (xAI)?", "what-is-grok", "Glossary", "AI Search", "ai_engines_answer_products", "TOFU", "NEW"),
 row("What is DeepSeek?", "what-is-deepseek", "Glossary", "AI Search", "ai_engines_answer_products", "TOFU", "NEW"),
 row("What is Search Generative Experience (SGE)?", "what-is-sge", "Glossary", "AI Search", "ai_engines_answer_products", "TOFU", "NEW"),
 row("What is an AI agent?", "what-is-an-ai-agent", "Glossary", "AI Search", "agentic_ai_search", "TOFU", "NEW"),
 row("What is chunking (content)?", "what-is-chunking", "Glossary", "Content", "how_ai_search_works", "TOFU", "NEW"),
 row("What is reranking?", "what-is-reranking", "Glossary", "AI Search", "how_ai_search_works", "TOFU", "NEW"),
 row("How to repurpose one asset for AI distribution (distribution-first GEO)", "repurpose-for-ai-distribution", "Blog", "Content", "agency_geo_frameworks", "MOFU", "NEW", "Y",
     "Distribution-first workflow",
     q("Walk me through turning one asset into many AI-discoverable surfaces.",
       "Why does distribution beat creation for AI visibility?",
       "What's the repurposing system you'd recommend?"),
     "Experience + Pull-quote", "Pull from client work"),
 row("How to build a brand-mention engine for AI citations", "brand-mention-engine", "Blog", "Authority", "offsite_brand_presence", "MOFU", "NEW", "Y",
     "Systematising earned mentions",
     q("How do you systematically earn the off-site mentions AI pulls from?",
       "What outreach actually works for this vs what wastes time?",
       "How do you measure mention growth against citations?"),
     "Experience", "Pull from client work"),
 row("Best AEO tools", "best-aeo-tools", "Listicle", "AI Search", "geo_aeo_tracking_tools", "MOFU", "NEW — SERP is listicle-shaped"),
]
goal4 += [
 row("How to do AI SEO for edtech SaaS", "ai-seo-for-edtech", "Blog", "Segment", "funnel_buyer_context", "MOFU", "NEW — edtech-marketing-agency exists", "Y",
     "Edtech AI-search nuances",
     q("What's specific about AI-search buyer research in edtech?",
       "What do edtech brands get wrong about AI SEO?",
       "Which content earns citations with educators/buyers?"),
     "Experience", "Pull from client work"),
 row("How to do AI SEO for legaltech SaaS", "ai-seo-for-legaltech", "Blog", "Segment", "funnel_buyer_context", "MOFU", "NEW — legaltech-marketing-agency exists", "Y",
     "Legaltech AI-search (YMYL/accuracy)",
     q("How do you build the authority legaltech needs for AI citations?",
       "What's riskiest about AI SEO in a YMYL legal context?",
       "How do you handle accuracy/citation standards?"),
     "Experience", "Pull from client work"),
 row("How to do AI SEO for proptech SaaS", "ai-seo-for-proptech", "Blog", "Segment", "funnel_buyer_context", "MOFU", "NEW — proptech-marketing-agency exists", "Y",
     "Proptech AI-search nuances",
     q("What's specific about AI-search visibility in proptech?",
       "Where do proptech brands under-invest in AI SEO?",
       "Which content types win here?"),
     "Experience", "Pull from client work"),
 row("How to do AI SEO for insurtech SaaS", "ai-seo-for-insurtech", "Blog", "Segment", "funnel_buyer_context", "MOFU", "NEW — insurancetech-marketing-agency exists", "Y",
     "Insurtech AI-search (YMYL/trust)",
     q("How do you earn AI citations in a trust-heavy insurance category?",
       "What do insurtech brands get wrong about AI SEO?",
       "How does compliance shape the content?"),
     "Experience", "Pull from client work"),
]
goal5 += [
 row("What is marketing attribution?", "what-is-marketing-attribution", "Glossary", "Strategy", "ai_visibility_metrics", "TOFU", "NEW"),
 row("How to model AI SEO in your marketing budget", "model-ai-seo-in-budget", "Blog", "Strategy", "ai_visibility_metrics", "MOFU", "NEW", "Y",
     "Budgeting for AI SEO",
     q("How do you carve out AI-SEO budget without raiding core SEO?",
       "What budget split do you advise at different stages?",
       "How do you justify the spend before results land?"),
     "Experience", "Pull from client work"),
]
goal6 += [
 row("What is sentiment analysis (for AI answers)?", "what-is-sentiment-analysis", "Glossary", "AI Search", "ai_visibility_metrics", "TOFU", "NEW"),
 row("What is a knowledge base (for LLMs)?", "what-is-a-knowledge-base", "Glossary", "AI Search", "knowledge_graph_entities", "TOFU", "NEW"),
 row("How to run a quarterly AI visibility review", "quarterly-ai-visibility-review", "Blog", "AI Search", "ai_visibility_metrics", "MOFU", "NEW", "Y",
     "Quarterly review cadence",
     q("What does our quarterly AI-visibility review actually cover?",
       "What decisions come out of it?",
       "What do teams skip that they shouldn't?"),
     "Experience", "team stack"),
 row("Best AI SEO learning resources & communities", "best-ai-seo-learning-resources", "Listicle", "Strategy", "ai_seo_events_publications", "MOFU", "NEW — SERP is listicle-shaped"),
]

# =====================================================================
# WRITE CSVs
# =====================================================================
sheets = {
    "00-Pillars": ("AI SEO Content Plan — Pillars", pillars),
    "01-Goal-Get-Discovered": ("AI SEO Content Plan — Get Discovered by AI", goal1),
    "02-Goal-Win-the-Citation": ("AI SEO Content Plan — Win the Citation", goal2),
    "03-Goal-Win-on-AI-Surfaces": ("AI SEO Content Plan — Win on AI Surfaces (GEO/AEO)", goal3),
    "04-Goal-Convert": ("AI SEO Content Plan — Convert AI-Sourced Visitors", goal4),
    "05-Goal-Pipeline-ROI": ("AI SEO Content Plan — Pipeline & ROI", goal5),
    "06-Goal-Measure-Scale": ("AI SEO Content Plan — Measure, Scale & Sustain", goal6),
}

total = 0
print(f"{'FILE':<34}{'ROWS':>5}  TITLE")
for fname, (title, rows) in sheets.items():
    path = os.path.join(OUT, fname + ".csv")
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS)
        w.writeheader()
        for r in rows:
            w.writerow(r)
    # base64 size check (per spec: <= ~21000 chars, no stray spaces)
    with open(path, "rb") as f:
        b64 = base64.b64encode(f.read()).decode()
    assert " " not in b64, f"stray space in base64 for {fname}"
    assert len(b64) <= 21000, f"{fname} base64 too large: {len(b64)}"
    total += len(rows)
    print(f"{fname+'.csv':<34}{len(rows):>5}  {title}  [b64 {len(b64)} chars OK]")

print(f"\nTOTAL: {total} rows across {len(sheets)} sheets")
