#!/usr/bin/env python3
"""
Run a dry-run interlinking pass across all Hugo content and emit a
structured audit report:
  - audit/interlink_opportunities.md   (human-readable, grouped per source file)
  - audit/interlink_opportunities.csv  (one row per opportunity)

Uses the merged LINK_MAP (curated glossary + auto-generated targets) and
all the rules in add_interlinks.py (flow routing, w-450 floor, per-paragraph
dedupe, self-link suppression, cluster-aware P0 promotion).
"""
import csv
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

import add_interlinks as ai
from link_map_generated import GENERATED_LINK_MAP

# Merge curated + generated map
ai.LINK_MAP = ai.LINK_MAP + GENERATED_LINK_MAP

OUT_DIR = ROOT / "audit"
OUT_DIR.mkdir(exist_ok=True)
MD_OUT = OUT_DIR / "interlink_opportunities.md"
CSV_OUT = OUT_DIR / "interlink_opportunities.csv"

# Walk every content file
entries = ai.collect_files(list(ai.CONTENT_TYPES.keys()))

rows = []  # one per potential link
for fpath, ctype, wgate in entries:
    _, log, err = ai.process_file(fpath, skip_faq=False, word_gate=wgate, source_type=ctype)
    if err or not log:
        continue
    rel = fpath.relative_to(ROOT)
    src_slug = fpath.stem
    src_cluster_entry = None
    # Look up source cluster via self_paths
    fm_block, _ = ai.split_frontmatter(fpath.read_text(encoding="utf-8"))
    for sp in ai.own_url_paths(fpath, fm_block):
        if sp in ai.CONTENT_CLUSTERS:
            src_cluster_entry = ai.CONTENT_CLUSTERS[sp]
            break
    src_cluster = (src_cluster_entry[0] if src_cluster_entry else "")

    for entry in log:
        tgt = entry["target"].rstrip("/") + "/"
        tgt_cluster_entry = ai.CONTENT_CLUSTERS.get(tgt)
        tgt_cluster = (tgt_cluster_entry[0] if tgt_cluster_entry else "")
        # destination type per add_interlinks.classify_target
        dst_type = ai.classify_target(entry["target"])
        rows.append({
            "source_type": ctype,
            "source_slug": src_slug,
            "source_cluster": src_cluster,
            "source_path": str(rel),
            "method": entry.get("method", "existing_phrase"),
            "anchor": entry["anchor"],
            "target": entry["target"],
            "destination_type": dst_type,
            "target_cluster": tgt_cluster,
            "priority": entry["priority"],
            "word_pos": entry["word_pos"],
        })

# ---------- Aggregates ----------
by_src_type = Counter(r["source_type"] for r in rows)
by_dst_type = Counter(r["destination_type"] for r in rows)
by_priority = Counter(r["priority"] for r in rows)
by_method = Counter(r["method"] for r in rows)
by_src_cluster = Counter(r["source_cluster"] for r in rows)
by_target_cluster = Counter(r["target_cluster"] for r in rows)

# Files affected
src_files_with_opps = defaultdict(list)
for r in rows:
    src_files_with_opps[(r["source_type"], r["source_slug"])].append(r)

# ---------- CSV ----------
with CSV_OUT.open("w", newline="", encoding="utf-8") as fp:
    w = csv.DictWriter(fp, fieldnames=[
        "source_type", "source_slug", "source_cluster", "source_path",
        "method", "destination_type", "target_cluster", "anchor", "target",
        "priority", "word_pos",
    ])
    w.writeheader()
    for r in rows:
        w.writerow(r)

# ---------- Markdown ----------
lines = [
    "# Interlinking Audit — opportunities discovered",
    "",
    f"_{len(rows)} potential new internal links across "
    f"{len(src_files_with_opps)} source files._",
    "",
    "Generated by `scripts/audit_interlink_opportunities.py`. All listed opportunities "
    "respect the documented routing rules (flow allow-list, w-450 floor for blogs, "
    "per-paragraph dedupe, self-link suppression).",
    "",
    "## Summary",
    "",
    "**By source content type:**",
]
src_type_order = ["blogs", "list", "glossary", "compare", "alternative"]
for t in src_type_order:
    c = by_src_type.get(t, 0)
    lines.append(f"- {t}: {c} opportunities")
lines += [
    "",
    "**By destination type:**",
]
for t, c in by_dst_type.most_common():
    lines.append(f"- → {t}: {c}")
lines += [
    "",
    "**By method:**",
]
for m, c in by_method.most_common():
    lines.append(f"- {m}: {c}")
lines += [
    "",
    "**By priority (after cluster promotion):**",
]
for p in ("P0", "P1", "P2"):
    c = by_priority.get(p, 0)
    lines.append(f"- {p}: {c}")
lines += [
    "",
    "**Top source clusters (most opportunities to add):**",
    "",
    "| Cluster | Opportunities |",
    "|---|---:|",
]
for c, n in by_src_cluster.most_common(12):
    if not c: continue
    lines.append(f"| {c} | {n} |")
lines += [
    "",
    "**Top target clusters (most often linked TO):**",
    "",
    "| Cluster | Times linked |",
    "|---|---:|",
]
for c, n in by_target_cluster.most_common(12):
    if not c: continue
    lines.append(f"| {c} | {n} |")

# ---------- Per-file detail ----------
lines += [
    "",
    "## Per-file detail",
    "",
    "Source files with the most opportunities first.",
    "",
]
sorted_files = sorted(src_files_with_opps.items(), key=lambda kv: -len(kv[1]))
for (stype, slug), file_rows in sorted_files:
    src_cluster = file_rows[0]["source_cluster"]
    lines.append(f"### `[{stype}]` {slug}  ·  cluster: `{src_cluster}`  ·  {len(file_rows)} opportunities")
    lines.append("")
    lines.append("| Priority | Method | Anchor | Target | Cluster | Word pos |")
    lines.append("|---|---|---|---|---|---:|")
    for r in sorted(file_rows, key=lambda x: (x["priority"], -x["word_pos"])):
        anchor = r["anchor"].replace("|", "\\|")
        target_cluster = r["target_cluster"] or "—"
        method_label = "**new sentence**" if r["method"] == "new_sentence" else "existing phrase"
        lines.append(
            f"| {r['priority']} | {method_label} | `{anchor}` | {r['target']} | {target_cluster} | {r['word_pos']} |"
        )
    lines.append("")

MD_OUT.write_text("\n".join(lines), encoding="utf-8")

print(f"Wrote {MD_OUT}")
print(f"Wrote {CSV_OUT}")
print()
print(f"TOTAL: {len(rows)} potential interlinks across {len(src_files_with_opps)} source files")
print()
print("By source type:")
for t in src_type_order:
    print(f"  {t:12s} {by_src_type.get(t,0):>4}")
print()
print("By destination type:")
for t, n in by_dst_type.most_common():
    print(f"  → {t:12s} {n:>4}")
print()
print("By method:")
for m, n in by_method.most_common():
    print(f"  {m}: {n}")
print()
print("By priority:")
for p in ("P0", "P1", "P2"):
    print(f"  {p}: {by_priority.get(p,0)}")
