#!/usr/bin/env python3
"""Auto-generated from clusters_source.csv. Do not hand-edit — re-run
scripts/build_clusters.py after changing the CSV.
"""

# 136 files across 20 clusters

CONTENT_CLUSTERS = {
    "/blogs/ai-seo-statistics/": ("ai-seo",),
    "/blogs/b2b-content-marketing-guide/": ("b2b-content-marketing",),
    "/blogs/b2b-demand-generation-guide/": ("b2b-demand-gen",),
    "/blogs/b2b-inbound-marketing-guide/": ("b2b-marketing",),
    "/blogs/b2b-lead-generation/": ("b2b-lead-gen",),
    "/blogs/b2b-linkedin-marketing-guide/": ("b2b-linkedin",),
    "/blogs/b2b-marketing-operations-guide/": ("b2b-marketing",),
    "/blogs/b2b-marketing/": ("b2b-marketing",),
    "/blogs/b2b-ppc-guide/": ("b2b-ppc",),
    "/blogs/b2b-ppc/": ("b2b-ppc",),
    "/blogs/b2b-saas-seo/": ("saas-seo",),
    "/blogs/enterprise-saas-seo-guide/": ("enterprise-seo",),
    "/blogs/enterprise-seo-challenges-and-fixes/": ("enterprise-seo",),
    "/blogs/enterprise-seo-guide/": ("enterprise-seo",),
    "/blogs/enterprise-seo-strategy-and-framework/": ("enterprise-seo",),
    "/blogs/fintech-seo-guide/": ("fintech-marketing",),
    "/blogs/how-do-i-run-linkedin-ads-for-saas-an-experts-take/": ("saas-ppc",),
    "/blogs/how-to-do-saas-content-audit/": ("saas-seo",),
    "/blogs/how-to-do-saas-seo-competitor-analysis/": ("saas-seo",),
    "/blogs/how-to-do-saas-seo-keyword-research/": ("saas-seo",),
    "/blogs/how-to-rank-on-chatgpt-in-2026-strategies-and-tips/": ("ai-seo",),
    "/blogs/how-to-run-google-ads-for-saas/": ("saas-ppc",),
    "/blogs/how-to-run-linkedin-retargeting-ads/": ("saas-ppc",),
    "/blogs/how-to-write-google-ads-copy-for-saas-in-2026/": ("saas-ppc",),
    "/blogs/how-to-write-saas-comparison-pages-for-seo/": ("saas-seo",),
    "/blogs/how-to-write-saas-seo-content-with-ai-that-actually-ranks/": ("saas-seo",),
    "/blogs/linkedin-account-based-marketing/": ("saas-linkedin",),
    "/blogs/optimize-saas-landing-pages-for-seo/": ("saas-seo",),
    "/blogs/saas-content-marketing-guide/": ("saas-content-marketing",),
    "/blogs/saas-link-building/": ("saas-seo",),
    "/blogs/saas-linkedin-ads-mistakes-to-avoid/": ("saas-linkedin",),
    "/blogs/saas-marketing-challenges-and-fixes/": ("saas-seo",),
    "/blogs/saas-ppc-checklist/": ("saas-ppc",),
    "/blogs/saas-ppc/": ("saas-ppc",),
    "/blogs/saas-seo-checklist/": ("saas-seo",),
    "/blogs/saas-seo-strategies-and-framework/": ("saas-seo",),
    "/blogs/saas-seo/": ("saas-seo",),
    "/blogs/the-8-common-saas-google-ads-mistakes-to-avoid-in-2026/": ("saas-ppc",),
    "/blogs/the-no-nonsense-guide-to-auditing-your-saas-ppc-account/": ("saas-ppc",),
    "/glossary/what-are-keyword-clusters/": ("seo-basics",),
    "/glossary/what-is-a-301-redirect/": ("seo-basics",),
    "/glossary/what-is-a-backlink/": ("seo-basics",),
    "/glossary/what-is-a-canonical-tag/": ("seo-basics",),
    "/glossary/what-is-a-long-tail-keyword/": ("seo-basics",),
    "/glossary/what-is-a-meta-description/": ("seo-basics",),
    "/glossary/what-is-abm/": ("b2b-lead-gen",),
    "/glossary/what-is-ai-hallucination/": ("ai-seo",),
    "/glossary/what-is-an-llm/": ("ai-seo",),
    "/glossary/what-is-an-seo-audit/": ("seo-basics",),
    "/glossary/what-is-anchor-text/": ("seo-basics",),
    "/glossary/what-is-arr/": ("digital-marketing-metrics",),
    "/glossary/what-is-brand-identity/": ("brand-marketing",),
    "/glossary/what-is-brand-positioning/": ("brand-marketing",),
    "/glossary/what-is-cls/": ("digital-marketing-metrics",),
    "/glossary/what-is-clv/": ("digital-marketing-metrics",),
    "/glossary/what-is-content-marketing/": ("saas-marketing",),
    "/glossary/what-is-conversion-rate/": ("digital-marketing-metrics",),
    "/glossary/what-is-cost-per-click/": ("digital-marketing-metrics",),
    "/glossary/what-is-cpa/": ("digital-marketing-metrics",),
    "/glossary/what-is-cpm/": ("digital-marketing-metrics",),
    "/glossary/what-is-crawling/": ("seo-basics",),
    "/glossary/what-is-ctr/": ("digital-marketing-metrics",),
    "/glossary/what-is-domain-authority/": ("seo-basics",),
    "/glossary/what-is-employer-branding/": ("brand-marketing",),
    "/glossary/what-is-evergreen-content/": ("seo-basics",),
    "/glossary/what-is-fid/": ("digital-marketing-metrics",),
    "/glossary/what-is-ga4/": ("marketing-analytics",),
    "/glossary/what-is-go-to-market-strategy/": ("saas-marketing",),
    "/glossary/what-is-google-ads/": ("saas-ppc",),
    "/glossary/what-is-google-search-console/": ("seo-basics",),
    "/glossary/what-is-google-tag-manager/": ("marketing-analytics",),
    "/glossary/what-is-gpt/": ("ai-seo",),
    "/glossary/what-is-icp/": ("digital-marketing-metrics",),
    "/glossary/what-is-image-alt-text/": ("seo-basics",),
    "/glossary/what-is-inbound-marketing/": ("saas-marketing",),
    "/glossary/what-is-indexing/": ("seo-basics",),
    "/glossary/what-is-keyword-research/": ("saas-marketing",),
    "/glossary/what-is-lead-generation/": ("b2b-lead-gen",),
    "/glossary/what-is-meta-ads/": ("ppc-basics",),
    "/glossary/what-is-nrr/": ("digital-marketing-metrics",),
    "/glossary/what-is-off-page-seo/": ("seo-basics",),
    "/glossary/what-is-on-page-seo/": ("seo-basics",),
    "/glossary/what-is-performance-marketing/": ("saas-ppc",),
    "/glossary/what-is-ppc/": ("ppc-basics",),
    "/glossary/what-is-programmatic-advertising/": ("ppc-basics",),
    "/glossary/what-is-prompt-engineering/": ("ai-seo",),
    "/glossary/what-is-rag/": ("ai-seo",),
    "/glossary/what-is-roas/": ("digital-marketing-metrics",),
    "/glossary/what-is-robots-txt/": ("seo-basics",),
    "/glossary/what-is-runway/": ("digital-marketing-metrics",),
    "/glossary/what-is-sal-in-saas/": ("digital-marketing-metrics",),
    "/glossary/what-is-schema-markup/": ("seo-basics",),
    "/glossary/what-is-sem/": ("digital-marketing-metrics",),
    "/glossary/what-is-seo/": ("seo-basics",),
    "/glossary/what-is-serp/": ("seo-basics",),
    "/glossary/what-is-ssl-certificate/": ("seo-basics",),
    "/glossary/what-is-ssp/": ("ppc-basics",),
    "/glossary/what-is-structured-data/": ("seo-basics",),
    "/glossary/what-is-tam-sam-som/": ("digital-marketing-metrics",),
    "/glossary/what-is-technical-seo/": ("seo-basics",),
    "/glossary/what-is-third-party-cookies/": ("marketing-analytics",),
    "/glossary/what-is-thought-leadership/": ("seo-basics",),
    "/glossary/what-is-upsell/": ("digital-marketing-metrics",),
    "/glossary/what-is-user-generated-content/": ("seo-basics",),
    "/list/best-aeo-agency/": ("ai-seo",),
    "/list/best-affordable-b2b-ppc-agencies/": ("b2b-ppc",),
    "/list/best-b2b-advertising-agencies/": ("b2b-ppc",),
    "/list/best-b2b-content-marketing-agencies/": ("b2b-content-marketing",),
    "/list/best-b2b-demand-generation-agencies/": ("b2b-demand-gen",),
    "/list/best-b2b-google-ads-agencies/": ("b2b-ppc",),
    "/list/best-b2b-lead-generation-companies/": ("b2b-lead-gen",),
    "/list/best-b2b-marketing-agencies/": ("b2b-marketing",),
    "/list/best-b2b-seo-agencies/": ("b2b-seo",),
    "/list/best-cybersecurity-marketing-agencies/": ("saas-marketing",),
    "/list/best-devtools-marketing-agencies/": ("saas-marketing",),
    "/list/best-edtech-marketing-agencies/": ("saas-marketing",),
    "/list/best-enterprise-seo-agencies/": ("enterprise-seo",),
    "/list/best-geo-agencies/": ("ai-seo",),
    "/list/best-healthtech-marketing-agencies/": ("saas-marketing",),
    "/list/best-hr-tech-marketing-agencies/": ("saas-marketing",),
    "/list/best-linkedin-marketing-agencies/": ("saas-linkedin",),
    "/list/best-martech-marketing-agencies/": ("saas-marketing",),
    "/list/best-proptech-marketing-agencies/": ("saas-marketing",),
    "/list/best-saas-content-marketing-agencies/": ("saas-content-marketing",),
    "/list/best-saas-geo-agencies/": ("ai-seo",),
    "/list/best-saas-growth-marketing-agencies/": ("saas-marketing",),
    "/list/best-saas-link-building-agencies/": ("saas-seo",),
    "/list/best-saas-marketing-agencies-2026/": ("saas-marketing",),
    "/list/best-saas-ppc-agencies/": ("saas-ppc",),
    "/list/best-saas-seo-agencies-for-startups/": ("saas-seo",),
    "/list/best-saas-seo-agencies/": ("saas-seo",),
    "/list/best-technical-seo-agencies/": ("saas-seo",),
    "/list/top-b2b-ppc-agencies/": ("b2b-ppc",),
    "/list/top-fintech-marketing-agencies/": ("fintech-marketing",),
    "/list/top-fintech-seo-agencies/": ("fintech-marketing",),
    "/list/top-performance-marketing-agencies/": ("b2b-ppc",),
}

CLUSTER_INDEX = {
    "ai-seo": {
        "blogs": [
            "/blogs/ai-seo-statistics/",
            "/blogs/how-to-rank-on-chatgpt-in-2026-strategies-and-tips/",
        ],
        "glossary": [
            "/glossary/what-is-ai-hallucination/",
            "/glossary/what-is-an-llm/",
            "/glossary/what-is-gpt/",
            "/glossary/what-is-prompt-engineering/",
            "/glossary/what-is-rag/",
        ],
        "list": [
            "/list/best-aeo-agency/",
            "/list/best-geo-agencies/",
            "/list/best-saas-geo-agencies/",
        ],
    },
    "b2b-content-marketing": {
        "blogs": [
            "/blogs/b2b-content-marketing-guide/",
        ],
        "list": [
            "/list/best-b2b-content-marketing-agencies/",
        ],
    },
    "b2b-demand-gen": {
        "blogs": [
            "/blogs/b2b-demand-generation-guide/",
        ],
        "list": [
            "/list/best-b2b-demand-generation-agencies/",
        ],
    },
    "b2b-lead-gen": {
        "blogs": [
            "/blogs/b2b-lead-generation/",
        ],
        "glossary": [
            "/glossary/what-is-abm/",
            "/glossary/what-is-lead-generation/",
        ],
        "list": [
            "/list/best-b2b-lead-generation-companies/",
        ],
    },
    "b2b-linkedin": {
        "blogs": [
            "/blogs/b2b-linkedin-marketing-guide/",
        ],
    },
    "b2b-marketing": {
        "blogs": [
            "/blogs/b2b-inbound-marketing-guide/",
            "/blogs/b2b-marketing-operations-guide/",
            "/blogs/b2b-marketing/",
        ],
        "list": [
            "/list/best-b2b-marketing-agencies/",
        ],
    },
    "b2b-ppc": {
        "blogs": [
            "/blogs/b2b-ppc-guide/",
            "/blogs/b2b-ppc/",
        ],
        "list": [
            "/list/best-affordable-b2b-ppc-agencies/",
            "/list/best-b2b-advertising-agencies/",
            "/list/best-b2b-google-ads-agencies/",
            "/list/top-b2b-ppc-agencies/",
            "/list/top-performance-marketing-agencies/",
        ],
    },
    "b2b-seo": {
        "list": [
            "/list/best-b2b-seo-agencies/",
        ],
    },
    "brand-marketing": {
        "glossary": [
            "/glossary/what-is-brand-identity/",
            "/glossary/what-is-brand-positioning/",
            "/glossary/what-is-employer-branding/",
        ],
    },
    "digital-marketing-metrics": {
        "glossary": [
            "/glossary/what-is-arr/",
            "/glossary/what-is-cls/",
            "/glossary/what-is-clv/",
            "/glossary/what-is-conversion-rate/",
            "/glossary/what-is-cost-per-click/",
            "/glossary/what-is-cpa/",
            "/glossary/what-is-cpm/",
            "/glossary/what-is-ctr/",
            "/glossary/what-is-fid/",
            "/glossary/what-is-icp/",
            "/glossary/what-is-nrr/",
            "/glossary/what-is-roas/",
            "/glossary/what-is-runway/",
            "/glossary/what-is-sal-in-saas/",
            "/glossary/what-is-sem/",
            "/glossary/what-is-tam-sam-som/",
            "/glossary/what-is-upsell/",
        ],
    },
    "enterprise-seo": {
        "blogs": [
            "/blogs/enterprise-saas-seo-guide/",
            "/blogs/enterprise-seo-challenges-and-fixes/",
            "/blogs/enterprise-seo-guide/",
            "/blogs/enterprise-seo-strategy-and-framework/",
        ],
        "list": [
            "/list/best-enterprise-seo-agencies/",
        ],
    },
    "fintech-marketing": {
        "blogs": [
            "/blogs/fintech-seo-guide/",
        ],
        "list": [
            "/list/top-fintech-marketing-agencies/",
            "/list/top-fintech-seo-agencies/",
        ],
    },
    "marketing-analytics": {
        "glossary": [
            "/glossary/what-is-ga4/",
            "/glossary/what-is-google-tag-manager/",
            "/glossary/what-is-third-party-cookies/",
        ],
    },
    "ppc-basics": {
        "glossary": [
            "/glossary/what-is-meta-ads/",
            "/glossary/what-is-ppc/",
            "/glossary/what-is-programmatic-advertising/",
            "/glossary/what-is-ssp/",
        ],
    },
    "saas-content-marketing": {
        "blogs": [
            "/blogs/saas-content-marketing-guide/",
        ],
        "list": [
            "/list/best-saas-content-marketing-agencies/",
        ],
    },
    "saas-linkedin": {
        "blogs": [
            "/blogs/linkedin-account-based-marketing/",
            "/blogs/saas-linkedin-ads-mistakes-to-avoid/",
        ],
        "list": [
            "/list/best-linkedin-marketing-agencies/",
        ],
    },
    "saas-marketing": {
        "glossary": [
            "/glossary/what-is-content-marketing/",
            "/glossary/what-is-go-to-market-strategy/",
            "/glossary/what-is-inbound-marketing/",
            "/glossary/what-is-keyword-research/",
        ],
        "list": [
            "/list/best-cybersecurity-marketing-agencies/",
            "/list/best-devtools-marketing-agencies/",
            "/list/best-edtech-marketing-agencies/",
            "/list/best-healthtech-marketing-agencies/",
            "/list/best-hr-tech-marketing-agencies/",
            "/list/best-martech-marketing-agencies/",
            "/list/best-proptech-marketing-agencies/",
            "/list/best-saas-growth-marketing-agencies/",
            "/list/best-saas-marketing-agencies-2026/",
        ],
    },
    "saas-ppc": {
        "blogs": [
            "/blogs/how-do-i-run-linkedin-ads-for-saas-an-experts-take/",
            "/blogs/how-to-run-google-ads-for-saas/",
            "/blogs/how-to-run-linkedin-retargeting-ads/",
            "/blogs/how-to-write-google-ads-copy-for-saas-in-2026/",
            "/blogs/saas-ppc-checklist/",
            "/blogs/saas-ppc/",
            "/blogs/the-8-common-saas-google-ads-mistakes-to-avoid-in-2026/",
            "/blogs/the-no-nonsense-guide-to-auditing-your-saas-ppc-account/",
        ],
        "glossary": [
            "/glossary/what-is-google-ads/",
            "/glossary/what-is-performance-marketing/",
        ],
        "list": [
            "/list/best-saas-ppc-agencies/",
        ],
    },
    "saas-seo": {
        "blogs": [
            "/blogs/b2b-saas-seo/",
            "/blogs/how-to-do-saas-content-audit/",
            "/blogs/how-to-do-saas-seo-competitor-analysis/",
            "/blogs/how-to-do-saas-seo-keyword-research/",
            "/blogs/how-to-write-saas-comparison-pages-for-seo/",
            "/blogs/how-to-write-saas-seo-content-with-ai-that-actually-ranks/",
            "/blogs/optimize-saas-landing-pages-for-seo/",
            "/blogs/saas-link-building/",
            "/blogs/saas-marketing-challenges-and-fixes/",
            "/blogs/saas-seo-checklist/",
            "/blogs/saas-seo-strategies-and-framework/",
            "/blogs/saas-seo/",
        ],
        "list": [
            "/list/best-saas-link-building-agencies/",
            "/list/best-saas-seo-agencies-for-startups/",
            "/list/best-saas-seo-agencies/",
            "/list/best-technical-seo-agencies/",
        ],
    },
    "seo-basics": {
        "glossary": [
            "/glossary/what-are-keyword-clusters/",
            "/glossary/what-is-a-301-redirect/",
            "/glossary/what-is-a-backlink/",
            "/glossary/what-is-a-canonical-tag/",
            "/glossary/what-is-a-long-tail-keyword/",
            "/glossary/what-is-a-meta-description/",
            "/glossary/what-is-an-seo-audit/",
            "/glossary/what-is-anchor-text/",
            "/glossary/what-is-crawling/",
            "/glossary/what-is-domain-authority/",
            "/glossary/what-is-evergreen-content/",
            "/glossary/what-is-google-search-console/",
            "/glossary/what-is-image-alt-text/",
            "/glossary/what-is-indexing/",
            "/glossary/what-is-off-page-seo/",
            "/glossary/what-is-on-page-seo/",
            "/glossary/what-is-robots-txt/",
            "/glossary/what-is-schema-markup/",
            "/glossary/what-is-seo/",
            "/glossary/what-is-serp/",
            "/glossary/what-is-ssl-certificate/",
            "/glossary/what-is-structured-data/",
            "/glossary/what-is-technical-seo/",
            "/glossary/what-is-thought-leadership/",
            "/glossary/what-is-user-generated-content/",
        ],
    },
}

# CLUSTER_AFFINITY: cluster → set of clusters considered same-topic
# for P0 promotion. Self-only by default (no cross-cluster matching).
CLUSTER_AFFINITY = {
    "ai-seo": {"ai-seo"},
    "b2b-content-marketing": {"b2b-content-marketing"},
    "b2b-demand-gen": {"b2b-demand-gen"},
    "b2b-lead-gen": {"b2b-lead-gen"},
    "b2b-linkedin": {"b2b-linkedin"},
    "b2b-marketing": {"b2b-marketing"},
    "b2b-ppc": {"b2b-ppc"},
    "b2b-seo": {"b2b-seo"},
    "brand-marketing": {"brand-marketing"},
    "digital-marketing-metrics": {"digital-marketing-metrics"},
    "enterprise-seo": {"enterprise-seo"},
    "fintech-marketing": {"fintech-marketing"},
    "marketing-analytics": {"marketing-analytics"},
    "ppc-basics": {"ppc-basics"},
    "saas-content-marketing": {"saas-content-marketing"},
    "saas-linkedin": {"saas-linkedin"},
    "saas-marketing": {"saas-marketing"},
    "saas-ppc": {"saas-ppc"},
    "saas-seo": {"saas-seo"},
    "seo-basics": {"seo-basics"},
}
